// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: cmltest.proto

package cmltest // import "git.pinquest.cn/qlb/cmltest"


import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	_ "git.pinquest.cn/qlb/brick/ext"
	core "git.pinquest.cn/qlb/core"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_Success                 ErrCode = 0
	ErrCode_ErrPermissionNotFound   ErrCode = 347001
	ErrCode_ErrRoleNotFound         ErrCode = 347002
	ErrCode_ErrUserRoleNotFound     ErrCode = 347003
	ErrCode_ErrRoleResourceNotFound ErrCode = 347004
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:      "Success",
		347001: "ErrPermissionNotFound",
		347002: "ErrRoleNotFound",
		347003: "ErrUserRoleNotFound",
		347004: "ErrRoleResourceNotFound",
	}
	ErrCode_value = map[string]int32{
		"Success":                 0,
		"ErrPermissionNotFound":   347001,
		"ErrRoleNotFound":         347002,
		"ErrUserRoleNotFound":     347003,
		"ErrRoleResourceNotFound": 347004,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_cmltest_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_cmltest_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{0}
}

type AppType int32

const (
	AppType_AppNil         AppType = 0  // 默认
	AppType_AppBiLin       AppType = 1  // 比邻
	AppType_AppQRobot      AppType = 2  // 圈客宝
	AppType_AppQOrder      AppType = 3  // 云订单
	AppType_AppQWhale      AppType = 4  // 鲸量
	AppType_AppQTk         AppType = 5  // 超级拓客
	AppType_AppQAICaller   AppType = 6  // ai电话
	AppType_AppRedPacket   AppType = 7  // 红包
	AppType_AppGroupCredit AppType = 8  // 群积分
	AppType_AppJQT         AppType = 9  // 京企通
	AppType_AppQMsg        AppType = 10 // 客服系统
)

// Enum value maps for AppType.
var (
	AppType_name = map[int32]string{
		0:  "AppNil",
		1:  "AppBiLin",
		2:  "AppQRobot",
		3:  "AppQOrder",
		4:  "AppQWhale",
		5:  "AppQTk",
		6:  "AppQAICaller",
		7:  "AppRedPacket",
		8:  "AppGroupCredit",
		9:  "AppJQT",
		10: "AppQMsg",
	}
	AppType_value = map[string]int32{
		"AppNil":         0,
		"AppBiLin":       1,
		"AppQRobot":      2,
		"AppQOrder":      3,
		"AppQWhale":      4,
		"AppQTk":         5,
		"AppQAICaller":   6,
		"AppRedPacket":   7,
		"AppGroupCredit": 8,
		"AppJQT":         9,
		"AppQMsg":        10,
	}
)

func (x AppType) Enum() *AppType {
	p := new(AppType)
	*p = x
	return p
}

func (x AppType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppType) Descriptor() protoreflect.EnumDescriptor {
	return file_cmltest_proto_enumTypes[1].Descriptor()
}

func (AppType) Type() protoreflect.EnumType {
	return &file_cmltest_proto_enumTypes[1]
}

func (x AppType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppType.Descriptor instead.
func (AppType) EnumDescriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{1}
}

// 资源类型
type ResourceType int32

const (
	ResourceType_ResourceTypeNil         ResourceType = 0
	ResourceType_ResourceTypeQrobot      ResourceType = 1 // 平台号
	ResourceType_ResourceTypeHostAccount ResourceType = 2 // 扫码号
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "ResourceTypeNil",
		1: "ResourceTypeQrobot",
		2: "ResourceTypeHostAccount",
	}
	ResourceType_value = map[string]int32{
		"ResourceTypeNil":         0,
		"ResourceTypeQrobot":      1,
		"ResourceTypeHostAccount": 2,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_cmltest_proto_enumTypes[2].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_cmltest_proto_enumTypes[2]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{2}
}

type ModelRole_RoleType int32

const (
	ModelRole_RoleTypeNil        ModelRole_RoleType = 0
	ModelRole_RoleTypeSuperAdmin ModelRole_RoleType = 1 // 超级管理组
	ModelRole_RoleTypeOperator   ModelRole_RoleType = 2 // 运营组
)

// Enum value maps for ModelRole_RoleType.
var (
	ModelRole_RoleType_name = map[int32]string{
		0: "RoleTypeNil",
		1: "RoleTypeSuperAdmin",
		2: "RoleTypeOperator",
	}
	ModelRole_RoleType_value = map[string]int32{
		"RoleTypeNil":        0,
		"RoleTypeSuperAdmin": 1,
		"RoleTypeOperator":   2,
	}
)

func (x ModelRole_RoleType) Enum() *ModelRole_RoleType {
	p := new(ModelRole_RoleType)
	*p = x
	return p
}

func (x ModelRole_RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelRole_RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_cmltest_proto_enumTypes[3].Descriptor()
}

func (ModelRole_RoleType) Type() protoreflect.EnumType {
	return &file_cmltest_proto_enumTypes[3]
}

func (x ModelRole_RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelRole_RoleType.Descriptor instead.
func (ModelRole_RoleType) EnumDescriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{0, 0}
}

type GetPermissionListReq_ListOption int32

const (
	GetPermissionListReq_ListOptionNil GetPermissionListReq_ListOption = 0
	// @type: uint32
	GetPermissionListReq_ListOptionAppType GetPermissionListReq_ListOption = 1
)

// Enum value maps for GetPermissionListReq_ListOption.
var (
	GetPermissionListReq_ListOption_name = map[int32]string{
		0: "ListOptionNil",
		1: "ListOptionAppType",
	}
	GetPermissionListReq_ListOption_value = map[string]int32{
		"ListOptionNil":     0,
		"ListOptionAppType": 1,
	}
)

func (x GetPermissionListReq_ListOption) Enum() *GetPermissionListReq_ListOption {
	p := new(GetPermissionListReq_ListOption)
	*p = x
	return p
}

func (x GetPermissionListReq_ListOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPermissionListReq_ListOption) Descriptor() protoreflect.EnumDescriptor {
	return file_cmltest_proto_enumTypes[4].Descriptor()
}

func (GetPermissionListReq_ListOption) Type() protoreflect.EnumType {
	return &file_cmltest_proto_enumTypes[4]
}

func (x GetPermissionListReq_ListOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPermissionListReq_ListOption.Descriptor instead.
func (GetPermissionListReq_ListOption) EnumDescriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{8, 0}
}

type GetRoleListReq_ListOption int32

const (
	GetRoleListReq_ListOptionNil GetRoleListReq_ListOption = 0
	// @type: string
	GetRoleListReq_ListOptionName GetRoleListReq_ListOption = 1
)

// Enum value maps for GetRoleListReq_ListOption.
var (
	GetRoleListReq_ListOption_name = map[int32]string{
		0: "ListOptionNil",
		1: "ListOptionName",
	}
	GetRoleListReq_ListOption_value = map[string]int32{
		"ListOptionNil":  0,
		"ListOptionName": 1,
	}
)

func (x GetRoleListReq_ListOption) Enum() *GetRoleListReq_ListOption {
	p := new(GetRoleListReq_ListOption)
	*p = x
	return p
}

func (x GetRoleListReq_ListOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetRoleListReq_ListOption) Descriptor() protoreflect.EnumDescriptor {
	return file_cmltest_proto_enumTypes[5].Descriptor()
}

func (GetRoleListReq_ListOption) Type() protoreflect.EnumType {
	return &file_cmltest_proto_enumTypes[5]
}

func (x GetRoleListReq_ListOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetRoleListReq_ListOption.Descriptor instead.
func (GetRoleListReq_ListOption) EnumDescriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{23, 0}
}

type GetUserRoleListSysReq_ListOption int32

const (
	GetUserRoleListSysReq_ListOptionNil GetUserRoleListSysReq_ListOption = 0
	// @type: uint64List
	GetUserRoleListSysReq_ListOptionUidList GetUserRoleListSysReq_ListOption = 1
)

// Enum value maps for GetUserRoleListSysReq_ListOption.
var (
	GetUserRoleListSysReq_ListOption_name = map[int32]string{
		0: "ListOptionNil",
		1: "ListOptionUidList",
	}
	GetUserRoleListSysReq_ListOption_value = map[string]int32{
		"ListOptionNil":     0,
		"ListOptionUidList": 1,
	}
)

func (x GetUserRoleListSysReq_ListOption) Enum() *GetUserRoleListSysReq_ListOption {
	p := new(GetUserRoleListSysReq_ListOption)
	*p = x
	return p
}

func (x GetUserRoleListSysReq_ListOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUserRoleListSysReq_ListOption) Descriptor() protoreflect.EnumDescriptor {
	return file_cmltest_proto_enumTypes[6].Descriptor()
}

func (GetUserRoleListSysReq_ListOption) Type() protoreflect.EnumType {
	return &file_cmltest_proto_enumTypes[6]
}

func (x GetUserRoleListSysReq_ListOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUserRoleListSysReq_ListOption.Descriptor instead.
func (GetUserRoleListSysReq_ListOption) EnumDescriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{25, 0}
}

type ModelRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt uint32 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt uint32 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt uint32 `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CorpId    uint32 `protobuf:"varint,5,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty"`
	AppId     uint32 `protobuf:"varint,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppType   uint32 `protobuf:"varint,7,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	// @ref_type: ModelRole.RoleType
	RoleType uint32 `protobuf:"varint,8,opt,name=role_type,json=roleType,proto3" json:"role_type,omitempty"`
	// @gorm: type:varchar(30)
	// @v: max=30
	Name string `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty" gorm:"type:varchar(30)" validate:"max=30"`
	// @desc: 小到大排序
	ViewOrder uint32 `protobuf:"varint,10,opt,name=view_order,json=viewOrder,proto3" json:"view_order,omitempty"`
	// @gorm: type: text
	Permission *ModelRole_Permission `protobuf:"bytes,11,opt,name=permission,proto3" json:"permission,omitempty" gorm:"type:text"`
}

func (x *ModelRole) Reset() {
	*x = ModelRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRole) ProtoMessage() {}

func (x *ModelRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRole.ProtoReflect.Descriptor instead.
func (*ModelRole) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{0}
}

func (x *ModelRole) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelRole) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelRole) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelRole) GetDeletedAt() uint32 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelRole) GetCorpId() uint32 {
	if x != nil {
		return x.CorpId
	}
	return 0
}

func (x *ModelRole) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ModelRole) GetAppType() uint32 {
	if x != nil {
		return x.AppType
	}
	return 0
}

func (x *ModelRole) GetRoleType() uint32 {
	if x != nil {
		return x.RoleType
	}
	return 0
}

func (x *ModelRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelRole) GetViewOrder() uint32 {
	if x != nil {
		return x.ViewOrder
	}
	return 0
}

func (x *ModelRole) GetPermission() *ModelRole_Permission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type ModelUserRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt uint32 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt uint32 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt uint32 `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CorpId    uint32 `protobuf:"varint,5,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty"`
	AppId     uint32 `protobuf:"varint,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Uid       uint64 `protobuf:"varint,7,opt,name=uid,proto3" json:"uid,omitempty"`
	RoleId    uint64 `protobuf:"varint,8,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
}

func (x *ModelUserRole) Reset() {
	*x = ModelUserRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelUserRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUserRole) ProtoMessage() {}

func (x *ModelUserRole) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUserRole.ProtoReflect.Descriptor instead.
func (*ModelUserRole) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{1}
}

func (x *ModelUserRole) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelUserRole) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelUserRole) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelUserRole) GetDeletedAt() uint32 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelUserRole) GetCorpId() uint32 {
	if x != nil {
		return x.CorpId
	}
	return 0
}

func (x *ModelUserRole) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ModelUserRole) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ModelUserRole) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

type ModelRoleResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt uint32 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt uint32 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt uint32 `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CorpId    uint32 `protobuf:"varint,5,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty"`
	AppId     uint32 `protobuf:"varint,6,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	RoleId    uint64 `protobuf:"varint,7,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	// @ref_type: ResourceType
	ResourceType uint32 `protobuf:"varint,8,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId   uint64 `protobuf:"varint,9,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
}

func (x *ModelRoleResource) Reset() {
	*x = ModelRoleResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelRoleResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRoleResource) ProtoMessage() {}

func (x *ModelRoleResource) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRoleResource.ProtoReflect.Descriptor instead.
func (*ModelRoleResource) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{2}
}

func (x *ModelRoleResource) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelRoleResource) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelRoleResource) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelRoleResource) GetDeletedAt() uint32 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelRoleResource) GetCorpId() uint32 {
	if x != nil {
		return x.CorpId
	}
	return 0
}

func (x *ModelRoleResource) GetAppId() uint32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *ModelRoleResource) GetRoleId() uint64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *ModelRoleResource) GetResourceType() uint32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *ModelRoleResource) GetResourceId() uint64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

type ModelPermission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt uint32 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt uint32 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt uint32 `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	ParentId  uint64 `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// @gorm: type: varchar(30)
	// @v: max=30
	Name string `protobuf:"bytes,11,opt,name=name,proto3" json:"name,omitempty" gorm:"type:varchar(30)" validate:"max=30"`
	// @gorm: type: varchar(100)
	// @v: max=100
	ConstId string `protobuf:"bytes,10,opt,name=const_id,json=constId,proto3" json:"const_id,omitempty" gorm:"type:varchar(100)" validate:"max=100"`
	// @desc: 模块
	AppType   uint32 `protobuf:"varint,6,opt,name=app_type,json=appType,proto3" json:"app_type,omitempty"`
	OrderView uint32 `protobuf:"varint,7,opt,name=order_view,json=orderView,proto3" json:"order_view,omitempty"`
	// @desc: 前端专属
	// @gorm: type: text
	// @v: max=1000
	Raw string `protobuf:"bytes,9,opt,name=raw,proto3" json:"raw,omitempty" gorm:"type:text" validate:"max=1000"`
}

func (x *ModelPermission) Reset() {
	*x = ModelPermission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelPermission) ProtoMessage() {}

func (x *ModelPermission) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelPermission.ProtoReflect.Descriptor instead.
func (*ModelPermission) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{3}
}

func (x *ModelPermission) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelPermission) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelPermission) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelPermission) GetDeletedAt() uint32 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelPermission) GetParentId() uint64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ModelPermission) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelPermission) GetConstId() string {
	if x != nil {
		return x.ConstId
	}
	return ""
}

func (x *ModelPermission) GetAppType() uint32 {
	if x != nil {
		return x.AppType
	}
	return 0
}

func (x *ModelPermission) GetOrderView() uint32 {
	if x != nil {
		return x.OrderView
	}
	return 0
}

func (x *ModelPermission) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

type AddPermissionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @v: required
	Permission *ModelPermission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty" validate:"required"`
}

func (x *AddPermissionReq) Reset() {
	*x = AddPermissionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPermissionReq) ProtoMessage() {}

func (x *AddPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPermissionReq.ProtoReflect.Descriptor instead.
func (*AddPermissionReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{4}
}

func (x *AddPermissionReq) GetPermission() *ModelPermission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type AddPermissionRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permission *ModelPermission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
}

func (x *AddPermissionRsp) Reset() {
	*x = AddPermissionRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPermissionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPermissionRsp) ProtoMessage() {}

func (x *AddPermissionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPermissionRsp.ProtoReflect.Descriptor instead.
func (*AddPermissionRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{5}
}

func (x *AddPermissionRsp) GetPermission() *ModelPermission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type SetPermissionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @v: required
	Permission *ModelPermission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty" validate:"required"`
}

func (x *SetPermissionReq) Reset() {
	*x = SetPermissionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPermissionReq) ProtoMessage() {}

func (x *SetPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPermissionReq.ProtoReflect.Descriptor instead.
func (*SetPermissionReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{6}
}

func (x *SetPermissionReq) GetPermission() *ModelPermission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type SetPermissionRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Permission *ModelPermission `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission,omitempty"`
}

func (x *SetPermissionRsp) Reset() {
	*x = SetPermissionRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPermissionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPermissionRsp) ProtoMessage() {}

func (x *SetPermissionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPermissionRsp.ProtoReflect.Descriptor instead.
func (*SetPermissionRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{7}
}

func (x *SetPermissionRsp) GetPermission() *ModelPermission {
	if x != nil {
		return x.Permission
	}
	return nil
}

type GetPermissionListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @v: required
	ListOption *core.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty" validate:"required"`
}

func (x *GetPermissionListReq) Reset() {
	*x = GetPermissionListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPermissionListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionListReq) ProtoMessage() {}

func (x *GetPermissionListReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionListReq.ProtoReflect.Descriptor instead.
func (*GetPermissionListReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{8}
}

func (x *GetPermissionListReq) GetListOption() *core.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type GetPermissionListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paginate *core.Paginate     `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	List     []*ModelPermission `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetPermissionListRsp) Reset() {
	*x = GetPermissionListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPermissionListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPermissionListRsp) ProtoMessage() {}

func (x *GetPermissionListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPermissionListRsp.ProtoReflect.Descriptor instead.
func (*GetPermissionListRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{9}
}

func (x *GetPermissionListRsp) GetPaginate() *core.Paginate {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *GetPermissionListRsp) GetList() []*ModelPermission {
	if x != nil {
		return x.List
	}
	return nil
}

type DelPermissionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @v: required
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" validate:"required"`
}

func (x *DelPermissionReq) Reset() {
	*x = DelPermissionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelPermissionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPermissionReq) ProtoMessage() {}

func (x *DelPermissionReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPermissionReq.ProtoReflect.Descriptor instead.
func (*DelPermissionReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{10}
}

func (x *DelPermissionReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelPermissionRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelPermissionRsp) Reset() {
	*x = DelPermissionRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelPermissionRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelPermissionRsp) ProtoMessage() {}

func (x *DelPermissionRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelPermissionRsp.ProtoReflect.Descriptor instead.
func (*DelPermissionRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{11}
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @ref_type: ResourceType
	ResourceType   uint32   `protobuf:"varint,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceIdList []uint64 `protobuf:"varint,2,rep,packed,name=resource_id_list,json=resourceIdList,proto3" json:"resource_id_list,omitempty"`
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{12}
}

func (x *Resource) GetResourceType() uint32 {
	if x != nil {
		return x.ResourceType
	}
	return 0
}

func (x *Resource) GetResourceIdList() []uint64 {
	if x != nil {
		return x.ResourceIdList
	}
	return nil
}

type AddRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @v: required
	Role         *ModelRole  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty" validate:"required"`
	UidList      []uint64    `protobuf:"varint,2,rep,packed,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
	ResourceList []*Resource `protobuf:"bytes,3,rep,name=resource_list,json=resourceList,proto3" json:"resource_list,omitempty"`
}

func (x *AddRoleReq) Reset() {
	*x = AddRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoleReq) ProtoMessage() {}

func (x *AddRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoleReq.ProtoReflect.Descriptor instead.
func (*AddRoleReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{13}
}

func (x *AddRoleReq) GetRole() *ModelRole {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *AddRoleReq) GetUidList() []uint64 {
	if x != nil {
		return x.UidList
	}
	return nil
}

func (x *AddRoleReq) GetResourceList() []*Resource {
	if x != nil {
		return x.ResourceList
	}
	return nil
}

type AddRoleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Role *ModelRole `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
}

func (x *AddRoleRsp) Reset() {
	*x = AddRoleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRoleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoleRsp) ProtoMessage() {}

func (x *AddRoleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoleRsp.ProtoReflect.Descriptor instead.
func (*AddRoleRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{14}
}

func (x *AddRoleRsp) GetRole() *ModelRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @v: required
	Role         *ModelRole  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty" validate:"required"`
	UidList      []uint64    `protobuf:"varint,2,rep,packed,name=uid_list,json=uidList,proto3" json:"uid_list,omitempty"`
	ResourceList []*Resource `protobuf:"bytes,3,rep,name=resource_list,json=resourceList,proto3" json:"resource_list,omitempty"`
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateRoleReq) GetRole() *ModelRole {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *UpdateRoleReq) GetUidList() []uint64 {
	if x != nil {
		return x.UidList
	}
	return nil
}

func (x *UpdateRoleReq) GetResourceList() []*Resource {
	if x != nil {
		return x.ResourceList
	}
	return nil
}

type UpdateRoleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateRoleRsp) Reset() {
	*x = UpdateRoleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRoleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRsp) ProtoMessage() {}

func (x *UpdateRoleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRsp.ProtoReflect.Descriptor instead.
func (*UpdateRoleRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{16}
}

type DelRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @v: required
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" validate:"required"`
}

func (x *DelRoleReq) Reset() {
	*x = DelRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRoleReq) ProtoMessage() {}

func (x *DelRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRoleReq.ProtoReflect.Descriptor instead.
func (*DelRoleReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{17}
}

func (x *DelRoleReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DelRoleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelRoleRsp) Reset() {
	*x = DelRoleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelRoleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRoleRsp) ProtoMessage() {}

func (x *DelRoleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRoleRsp.ProtoReflect.Descriptor instead.
func (*DelRoleRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{18}
}

type CopyRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @v: required
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" validate:"required"`
	// @v: max=30
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" validate:"max=30"`
}

func (x *CopyRoleReq) Reset() {
	*x = CopyRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRoleReq) ProtoMessage() {}

func (x *CopyRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRoleReq.ProtoReflect.Descriptor instead.
func (*CopyRoleReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{19}
}

func (x *CopyRoleReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CopyRoleReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CopyRoleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CopyRole *ModelRole `protobuf:"bytes,1,opt,name=copy_role,json=copyRole,proto3" json:"copy_role,omitempty"`
}

func (x *CopyRoleRsp) Reset() {
	*x = CopyRoleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CopyRoleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyRoleRsp) ProtoMessage() {}

func (x *CopyRoleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyRoleRsp.ProtoReflect.Descriptor instead.
func (*CopyRoleRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{20}
}

func (x *CopyRoleRsp) GetCopyRole() *ModelRole {
	if x != nil {
		return x.CopyRole
	}
	return nil
}

type SortRoleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoleList []*ModelRole `protobuf:"bytes,1,rep,name=role_list,json=roleList,proto3" json:"role_list,omitempty"`
}

func (x *SortRoleReq) Reset() {
	*x = SortRoleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortRoleReq) ProtoMessage() {}

func (x *SortRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortRoleReq.ProtoReflect.Descriptor instead.
func (*SortRoleReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{21}
}

func (x *SortRoleReq) GetRoleList() []*ModelRole {
	if x != nil {
		return x.RoleList
	}
	return nil
}

type SortRoleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SortRoleRsp) Reset() {
	*x = SortRoleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortRoleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortRoleRsp) ProtoMessage() {}

func (x *SortRoleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortRoleRsp.ProtoReflect.Descriptor instead.
func (*SortRoleRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{22}
}

type GetRoleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @v: required
	ListOption *core.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty" validate:"required"`
}

func (x *GetRoleListReq) Reset() {
	*x = GetRoleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListReq) ProtoMessage() {}

func (x *GetRoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListReq.ProtoReflect.Descriptor instead.
func (*GetRoleListReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{23}
}

func (x *GetRoleListReq) GetListOption() *core.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type GetRoleListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paginate *core.Paginate `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	List     []*ModelRole   `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetRoleListRsp) Reset() {
	*x = GetRoleListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRoleListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleListRsp) ProtoMessage() {}

func (x *GetRoleListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleListRsp.ProtoReflect.Descriptor instead.
func (*GetRoleListRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{24}
}

func (x *GetRoleListRsp) GetPaginate() *core.Paginate {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *GetRoleListRsp) GetList() []*ModelRole {
	if x != nil {
		return x.List
	}
	return nil
}

type GetUserRoleListSysReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @v: required
	ListOption *core.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty" validate:"required"`
	// @v: required
	CorpId uint32 `protobuf:"varint,2,opt,name=corp_id,json=corpId,proto3" json:"corp_id,omitempty" validate:"required"`
	// @v: required
	ApppId uint32 `protobuf:"varint,3,opt,name=appp_id,json=apppId,proto3" json:"appp_id,omitempty" validate:"required"`
}

func (x *GetUserRoleListSysReq) Reset() {
	*x = GetUserRoleListSysReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRoleListSysReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoleListSysReq) ProtoMessage() {}

func (x *GetUserRoleListSysReq) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoleListSysReq.ProtoReflect.Descriptor instead.
func (*GetUserRoleListSysReq) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserRoleListSysReq) GetListOption() *core.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

func (x *GetUserRoleListSysReq) GetCorpId() uint32 {
	if x != nil {
		return x.CorpId
	}
	return 0
}

func (x *GetUserRoleListSysReq) GetApppId() uint32 {
	if x != nil {
		return x.ApppId
	}
	return 0
}

type GetUserRoleListSysRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paginate *core.Paginate   `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	List     []*ModelUserRole `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetUserRoleListSysRsp) Reset() {
	*x = GetUserRoleListSysRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserRoleListSysRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRoleListSysRsp) ProtoMessage() {}

func (x *GetUserRoleListSysRsp) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRoleListSysRsp.ProtoReflect.Descriptor instead.
func (*GetUserRoleListSysRsp) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserRoleListSysRsp) GetPaginate() *core.Paginate {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *GetUserRoleListSysRsp) GetList() []*ModelUserRole {
	if x != nil {
		return x.List
	}
	return nil
}

type ModelRole_Permission struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @desc: key 为 service type
	PermissionMap map[uint32]*ModelRole_Permission_PermissionList `protobuf:"bytes,1,rep,name=permission_map,json=permissionMap,proto3" json:"permission_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ModelRole_Permission) Reset() {
	*x = ModelRole_Permission{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelRole_Permission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRole_Permission) ProtoMessage() {}

func (x *ModelRole_Permission) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRole_Permission.ProtoReflect.Descriptor instead.
func (*ModelRole_Permission) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ModelRole_Permission) GetPermissionMap() map[uint32]*ModelRole_Permission_PermissionList {
	if x != nil {
		return x.PermissionMap
	}
	return nil
}

type ModelRole_Permission_PermissionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermissionIdList    []uint64 `protobuf:"varint,1,rep,packed,name=permission_id_list,json=permissionIdList,proto3" json:"permission_id_list,omitempty"`
	MenuIdList          []uint64 `protobuf:"varint,2,rep,packed,name=menu_id_list,json=menuIdList,proto3" json:"menu_id_list,omitempty"`
	MenuTemplateConstId string   `protobuf:"bytes,3,opt,name=menu_template_const_id,json=menuTemplateConstId,proto3" json:"menu_template_const_id,omitempty"`
}

func (x *ModelRole_Permission_PermissionList) Reset() {
	*x = ModelRole_Permission_PermissionList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmltest_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelRole_Permission_PermissionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRole_Permission_PermissionList) ProtoMessage() {}

func (x *ModelRole_Permission_PermissionList) ProtoReflect() protoreflect.Message {
	mi := &file_cmltest_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRole_Permission_PermissionList.ProtoReflect.Descriptor instead.
func (*ModelRole_Permission_PermissionList) Descriptor() ([]byte, []int) {
	return file_cmltest_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *ModelRole_Permission_PermissionList) GetPermissionIdList() []uint64 {
	if x != nil {
		return x.PermissionIdList
	}
	return nil
}

func (x *ModelRole_Permission_PermissionList) GetMenuIdList() []uint64 {
	if x != nil {
		return x.MenuIdList
	}
	return nil
}

func (x *ModelRole_Permission_PermissionList) GetMenuTemplateConstId() string {
	if x != nil {
		return x.MenuTemplateConstId
	}
	return ""
}

var File_cmltest_proto protoreflect.FileDescriptor

var file_cmltest_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x65, 0x78, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8d, 0x06, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f,
	0x72, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x72,
	0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70,
	0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x70,
	0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x76, 0x69, 0x65, 0x77,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6d, 0x6c, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x2e, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x1a, 0xed, 0x02, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x57, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x63, 0x6d,
	0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x70,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x70, 0x1a, 0x95, 0x01, 0x0a,
	0x0e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x2c, 0x0a, 0x12, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x10, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0c, 0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x04, 0x52, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x33, 0x0a, 0x16, 0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x6d, 0x65, 0x6e, 0x75, 0x54, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x49, 0x64, 0x1a, 0x6e, 0x0a, 0x12, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x42, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x6d,
	0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x2e,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x49, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x4e, 0x69, 0x6c, 0x10,
	0x00, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x53, 0x75, 0x70,
	0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x6f, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x10, 0x02, 0x22,
	0xd7, 0x01, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x6f, 0x72, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x63, 0x6f, 0x72, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x8f, 0x02, 0x0a, 0x11, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x6f, 0x72, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63,
	0x6f, 0x72, 0x70, 0x49, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72,
	0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x22, 0x96, 0x02, 0x0a, 0x0f,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x70, 0x70, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x70, 0x70, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x76, 0x69, 0x65,
	0x77, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x56, 0x69,
	0x65, 0x77, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x72, 0x61, 0x77, 0x22, 0x4c, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x38, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63,
	0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0x4c, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6d, 0x6c,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x22, 0x4c, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x38, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4c,
	0x0a, 0x10, 0x53, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x73, 0x70, 0x12, 0x38, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x81, 0x01, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6c, 0x69,
	0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65, 0x10, 0x01,
	0x22, 0x70, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x08, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x22, 0x59, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x87, 0x01, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x75, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x07,
	0x75, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x34, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x26, 0x0a,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6d,
	0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x8a, 0x01, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x19, 0x0a, 0x08, 0x75, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x07, 0x75, 0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x0d, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x73, 0x70, 0x22, 0x1c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x22,
	0x31, 0x0a, 0x0b, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x0b, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73,
	0x70, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x6f, 0x70, 0x79, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x70, 0x79, 0x52, 0x6f,
	0x6c, 0x65, 0x22, 0x3e, 0x0a, 0x0b, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x2f, 0x0a, 0x09, 0x72, 0x6f, 0x6c, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x08, 0x72, 0x6f, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73,
	0x70, 0x22, 0x78, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x10, 0x01, 0x22, 0x64, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x2a, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x22, 0xb4, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x0b, 0x6c,
	0x69, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17,
	0x0a, 0x07, 0x63, 0x6f, 0x72, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x63, 0x6f, 0x72, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x70, 0x70, 0x70, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x70, 0x70, 0x70, 0x49, 0x64,
	0x22, 0x36, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x69, 0x6c, 0x10,
	0x00, 0x12, 0x15, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x55,
	0x69, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x10, 0x01, 0x22, 0x6f, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x52, 0x73,
	0x70, 0x12, 0x2a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x52, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6d,
	0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x6f, 0x6c, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x2a, 0x84, 0x01, 0x0a, 0x07, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x10, 0x00, 0x12, 0x1b, 0x0a, 0x15, 0x45, 0x72, 0x72, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0xf9, 0x96, 0x15, 0x12,
	0x15, 0x0a, 0x0f, 0x45, 0x72, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75,
	0x6e, 0x64, 0x10, 0xfa, 0x96, 0x15, 0x12, 0x19, 0x0a, 0x13, 0x45, 0x72, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x6f, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0xfb, 0x96,
	0x15, 0x12, 0x1d, 0x0a, 0x17, 0x45, 0x72, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0xfc, 0x96, 0x15,
	0x2a, 0xad, 0x01, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06,
	0x41, 0x70, 0x70, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x42,
	0x69, 0x4c, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x51, 0x52, 0x6f,
	0x62, 0x6f, 0x74, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x51, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x51, 0x57, 0x68, 0x61, 0x6c,
	0x65, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x51, 0x54, 0x6b, 0x10, 0x05, 0x12,
	0x10, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x51, 0x41, 0x49, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x10,
	0x06, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x70, 0x70, 0x52, 0x65, 0x64, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x10, 0x07, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x70, 0x70, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x43,
	0x72, 0x65, 0x64, 0x69, 0x74, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x4a, 0x51,
	0x54, 0x10, 0x09, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x70, 0x70, 0x51, 0x4d, 0x73, 0x67, 0x10, 0x0a,
	0x2a, 0x58, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x13, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x51, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x10, 0x01, 0x12, 0x1b, 0x0a,
	0x17, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x48, 0x6f, 0x73,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x10, 0x02, 0x32, 0x94, 0x06, 0x0a, 0x07, 0x63,
	0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x12, 0x51, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x50, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73,
	0x74, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x22, 0x0a, 0x9a,
	0xc8, 0xd0, 0x07, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x12, 0x51, 0x0a, 0x0d, 0x53, 0x65, 0x74,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x63, 0x6d, 0x6c,
	0x74, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x53, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70,
	0x22, 0x0a, 0x9a, 0xc8, 0xd0, 0x07, 0x05, 0x73, 0x74, 0x61, 0x66, 0x66, 0x12, 0x53, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x1d, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x1d, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x51, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c,
	0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e,
	0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x22, 0x0a, 0x9a, 0xc8, 0xd0, 0x07, 0x05, 0x73,
	0x74, 0x61, 0x66, 0x66, 0x12, 0x35, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12,
	0x13, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x41,
	0x64, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x63, 0x6d, 0x6c, 0x74,
	0x65, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x16, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x07, 0x44,
	0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74,
	0x2e, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x63, 0x6d,
	0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x65, 0x6c, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x38, 0x0a, 0x08, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14,
	0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x70, 0x79, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x43,
	0x6f, 0x70, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x08,
	0x53, 0x6f, 0x72, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x14, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14,
	0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x6f, 0x6c,
	0x65, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x17,
	0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6c, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x56, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x12,
	0x1e, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x1e, 0x2e, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x6f, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x79, 0x73, 0x52, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x72, 0x63, 0x2f, 0x63, 0x6d, 0x6c, 0x74, 0x65, 0x73, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmltest_proto_rawDescOnce sync.Once
	file_cmltest_proto_rawDescData = file_cmltest_proto_rawDesc
)

func file_cmltest_proto_rawDescGZIP() []byte {
	file_cmltest_proto_rawDescOnce.Do(func() {
		file_cmltest_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmltest_proto_rawDescData)
	})
	return file_cmltest_proto_rawDescData
}

var file_cmltest_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_cmltest_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_cmltest_proto_goTypes = []interface{}{
	(ErrCode)(0),                                // 0: cmltest.ErrCode
	(AppType)(0),                                // 1: cmltest.AppType
	(ResourceType)(0),                           // 2: cmltest.ResourceType
	(ModelRole_RoleType)(0),                     // 3: cmltest.ModelRole.RoleType
	(GetPermissionListReq_ListOption)(0),        // 4: cmltest.GetPermissionListReq.ListOption
	(GetRoleListReq_ListOption)(0),              // 5: cmltest.GetRoleListReq.ListOption
	(GetUserRoleListSysReq_ListOption)(0),       // 6: cmltest.GetUserRoleListSysReq.ListOption
	(*ModelRole)(nil),                           // 7: cmltest.ModelRole
	(*ModelUserRole)(nil),                       // 8: cmltest.ModelUserRole
	(*ModelRoleResource)(nil),                   // 9: cmltest.ModelRoleResource
	(*ModelPermission)(nil),                     // 10: cmltest.ModelPermission
	(*AddPermissionReq)(nil),                    // 11: cmltest.AddPermissionReq
	(*AddPermissionRsp)(nil),                    // 12: cmltest.AddPermissionRsp
	(*SetPermissionReq)(nil),                    // 13: cmltest.SetPermissionReq
	(*SetPermissionRsp)(nil),                    // 14: cmltest.SetPermissionRsp
	(*GetPermissionListReq)(nil),                // 15: cmltest.GetPermissionListReq
	(*GetPermissionListRsp)(nil),                // 16: cmltest.GetPermissionListRsp
	(*DelPermissionReq)(nil),                    // 17: cmltest.DelPermissionReq
	(*DelPermissionRsp)(nil),                    // 18: cmltest.DelPermissionRsp
	(*Resource)(nil),                            // 19: cmltest.Resource
	(*AddRoleReq)(nil),                          // 20: cmltest.AddRoleReq
	(*AddRoleRsp)(nil),                          // 21: cmltest.AddRoleRsp
	(*UpdateRoleReq)(nil),                       // 22: cmltest.UpdateRoleReq
	(*UpdateRoleRsp)(nil),                       // 23: cmltest.UpdateRoleRsp
	(*DelRoleReq)(nil),                          // 24: cmltest.DelRoleReq
	(*DelRoleRsp)(nil),                          // 25: cmltest.DelRoleRsp
	(*CopyRoleReq)(nil),                         // 26: cmltest.CopyRoleReq
	(*CopyRoleRsp)(nil),                         // 27: cmltest.CopyRoleRsp
	(*SortRoleReq)(nil),                         // 28: cmltest.SortRoleReq
	(*SortRoleRsp)(nil),                         // 29: cmltest.SortRoleRsp
	(*GetRoleListReq)(nil),                      // 30: cmltest.GetRoleListReq
	(*GetRoleListRsp)(nil),                      // 31: cmltest.GetRoleListRsp
	(*GetUserRoleListSysReq)(nil),               // 32: cmltest.GetUserRoleListSysReq
	(*GetUserRoleListSysRsp)(nil),               // 33: cmltest.GetUserRoleListSysRsp
	(*ModelRole_Permission)(nil),                // 34: cmltest.ModelRole.Permission
	(*ModelRole_Permission_PermissionList)(nil), // 35: cmltest.ModelRole.Permission.PermissionList
	nil,                     // 36: cmltest.ModelRole.Permission.PermissionMapEntry
	(*core.ListOption)(nil), // 37: core.ListOption
	(*core.Paginate)(nil),   // 38: core.Paginate
}
var file_cmltest_proto_depIdxs = []int32{
	34, // 0: cmltest.ModelRole.permission:type_name -> cmltest.ModelRole.Permission
	10, // 1: cmltest.AddPermissionReq.permission:type_name -> cmltest.ModelPermission
	10, // 2: cmltest.AddPermissionRsp.permission:type_name -> cmltest.ModelPermission
	10, // 3: cmltest.SetPermissionReq.permission:type_name -> cmltest.ModelPermission
	10, // 4: cmltest.SetPermissionRsp.permission:type_name -> cmltest.ModelPermission
	37, // 5: cmltest.GetPermissionListReq.list_option:type_name -> core.ListOption
	38, // 6: cmltest.GetPermissionListRsp.paginate:type_name -> core.Paginate
	10, // 7: cmltest.GetPermissionListRsp.list:type_name -> cmltest.ModelPermission
	7,  // 8: cmltest.AddRoleReq.role:type_name -> cmltest.ModelRole
	19, // 9: cmltest.AddRoleReq.resource_list:type_name -> cmltest.Resource
	7,  // 10: cmltest.AddRoleRsp.role:type_name -> cmltest.ModelRole
	7,  // 11: cmltest.UpdateRoleReq.role:type_name -> cmltest.ModelRole
	19, // 12: cmltest.UpdateRoleReq.resource_list:type_name -> cmltest.Resource
	7,  // 13: cmltest.CopyRoleRsp.copy_role:type_name -> cmltest.ModelRole
	7,  // 14: cmltest.SortRoleReq.role_list:type_name -> cmltest.ModelRole
	37, // 15: cmltest.GetRoleListReq.list_option:type_name -> core.ListOption
	38, // 16: cmltest.GetRoleListRsp.paginate:type_name -> core.Paginate
	7,  // 17: cmltest.GetRoleListRsp.list:type_name -> cmltest.ModelRole
	37, // 18: cmltest.GetUserRoleListSysReq.list_option:type_name -> core.ListOption
	38, // 19: cmltest.GetUserRoleListSysRsp.paginate:type_name -> core.Paginate
	8,  // 20: cmltest.GetUserRoleListSysRsp.list:type_name -> cmltest.ModelUserRole
	36, // 21: cmltest.ModelRole.Permission.permission_map:type_name -> cmltest.ModelRole.Permission.PermissionMapEntry
	35, // 22: cmltest.ModelRole.Permission.PermissionMapEntry.value:type_name -> cmltest.ModelRole.Permission.PermissionList
	11, // 23: cmltest.cmltest.AddPermission:input_type -> cmltest.AddPermissionReq
	13, // 24: cmltest.cmltest.SetPermission:input_type -> cmltest.SetPermissionReq
	15, // 25: cmltest.cmltest.GetPermissionList:input_type -> cmltest.GetPermissionListReq
	17, // 26: cmltest.cmltest.DelPermission:input_type -> cmltest.DelPermissionReq
	20, // 27: cmltest.cmltest.AddRole:input_type -> cmltest.AddRoleReq
	22, // 28: cmltest.cmltest.UpdateRole:input_type -> cmltest.UpdateRoleReq
	24, // 29: cmltest.cmltest.DelRole:input_type -> cmltest.DelRoleReq
	26, // 30: cmltest.cmltest.CopyRole:input_type -> cmltest.CopyRoleReq
	28, // 31: cmltest.cmltest.SortRole:input_type -> cmltest.SortRoleReq
	30, // 32: cmltest.cmltest.GetRoleList:input_type -> cmltest.GetRoleListReq
	32, // 33: cmltest.cmltest.GetUserRoleListSys:input_type -> cmltest.GetUserRoleListSysReq
	12, // 34: cmltest.cmltest.AddPermission:output_type -> cmltest.AddPermissionRsp
	14, // 35: cmltest.cmltest.SetPermission:output_type -> cmltest.SetPermissionRsp
	16, // 36: cmltest.cmltest.GetPermissionList:output_type -> cmltest.GetPermissionListRsp
	18, // 37: cmltest.cmltest.DelPermission:output_type -> cmltest.DelPermissionRsp
	21, // 38: cmltest.cmltest.AddRole:output_type -> cmltest.AddRoleRsp
	23, // 39: cmltest.cmltest.UpdateRole:output_type -> cmltest.UpdateRoleRsp
	25, // 40: cmltest.cmltest.DelRole:output_type -> cmltest.DelRoleRsp
	27, // 41: cmltest.cmltest.CopyRole:output_type -> cmltest.CopyRoleRsp
	29, // 42: cmltest.cmltest.SortRole:output_type -> cmltest.SortRoleRsp
	31, // 43: cmltest.cmltest.GetRoleList:output_type -> cmltest.GetRoleListRsp
	33, // 44: cmltest.cmltest.GetUserRoleListSys:output_type -> cmltest.GetUserRoleListSysRsp
	34, // [34:45] is the sub-list for method output_type
	23, // [23:34] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_cmltest_proto_init() }
func file_cmltest_proto_init() {
	if File_cmltest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmltest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelUserRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelRoleResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelPermission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPermissionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPermissionRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPermissionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPermissionRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPermissionListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPermissionListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelPermissionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelPermissionRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRoleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRoleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelRoleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CopyRoleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortRoleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortRoleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRoleListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRoleListSysReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserRoleListSysRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelRole_Permission); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmltest_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelRole_Permission_PermissionList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmltest_proto_rawDesc,
			NumEnums:      7,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmltest_proto_goTypes,
		DependencyIndexes: file_cmltest_proto_depIdxs,
		EnumInfos:         file_cmltest_proto_enumTypes,
		MessageInfos:      file_cmltest_proto_msgTypes,
	}.Build()
	File_cmltest_proto = out.File
	file_cmltest_proto_rawDesc = nil
	file_cmltest_proto_goTypes = nil
	file_cmltest_proto_depIdxs = nil
}
