// Code generated by rpc_gen. DO NOT EDIT.

package cmltestdb

import (
	"reflect"

	"git.pinquest.cn/qlb/brick/dbproxy"
)

var ModelRoleDetail = &dbproxy.ModelObjectType{
	Name: "cmltest.ModelRole.Detail",
	PrimaryKey: "",
	PrimaryKeyType: "",
	FieldList: &dbproxy.ObjectFieldList{
		List: []*dbproxy.ObjectField{
			{
				FieldName: "user_count",
				Type:      "uint32",
				RefType:   "",
				FormName:  "",
				FormType:  "",
				Validate:  "",
				DbDef:     "",
				ScopeCond: "",
				LinkTo:    "",
				Editable:  true,
				IsArray:   false,
			},
			{
				FieldName: "user_list",
				Type:      "object",
				RefType:   "quan.UserUnit",
				FormName:  "",
				FormType:  "",
				Validate:  "",
				DbDef:     "",
				ScopeCond: "",
				LinkTo:    "",
				Editable:  true,
				IsArray:   true,
			},
			{
				FieldName: "robot_list",
				Type:      "object",
				RefType:   "quan.UserUnit",
				FormName:  "",
				FormType:  "",
				Validate:  "",
				DbDef:     "",
				ScopeCond: "",
				LinkTo:    "",
				Editable:  true,
				IsArray:   true,
			},
		},
	},
}

func init() {
	ObjectTypeList = append(ObjectTypeList, ModelRoleDetail)
}

var UserCountModelRoleDetail = &dbproxy.StructField{
	StructFieldName: "UserCount",
	DbFieldName:     "user_count",
}

var UserListModelRoleDetail = &dbproxy.StructField{
	StructFieldName: "UserList",
	DbFieldName:     "user_list",
}

var RobotListModelRoleDetail = &dbproxy.StructField{
	StructFieldName: "RobotList",
	DbFieldName:     "robot_list",
}

type ModelRoleDetailReflect struct {
	UserCount dbproxy.StructFieldWithObj
	UserList dbproxy.StructFieldWithObj
	RobotList dbproxy.StructFieldWithObj
}

func NewModelRoleDetailReflect(i interface{}) *ModelRoleDetailReflect {
	obj := reflect.ValueOf(i)
	if obj.Kind() == reflect.Ptr {
	    obj = obj.Elem()
	}
	r := &ModelRoleDetailReflect{
		UserCount: dbproxy.StructFieldWithObj{Field: UserCountModelRoleDetail, Obj: obj},
		UserList: dbproxy.StructFieldWithObj{Field: UserListModelRoleDetail, Obj: obj},
		RobotList: dbproxy.StructFieldWithObj{Field: RobotListModelRoleDetail, Obj: obj},
	}

	return r
}

