// Code generated by rpc_gen. DO NOT EDIT.

package cmltestdb

import (
	"git.pinquest.cn/qlb/brick/dbproxy"
)

var ModelRoleRoleType = &dbproxy.ModelEnumType{
	Name: "cmltest.ModelRole.RoleType",
	FieldList: &dbproxy.EnumFieldList{
		List: []*dbproxy.EnumField{
			{
				FieldName: "RoleTypeSuperAdmin",
				IntValue:  1,
				FormName:  "",
			},
			{
				FieldName: "RoleTypeOperator",
				IntValue:  2,
				FormName:  "",
			},
		},
	},
}

func init() {
	EnumTypeList = append(EnumTypeList, ModelRoleRoleType)
}

