// Code generated by rpc_gen. DO NOT EDIT.

package cmltestdb

import (
	"reflect"

	"git.pinquest.cn/qlb/brick/dbproxy"
)

var ModelPermissionDetail = &dbproxy.ModelObjectType{
	Name: "cmltest.ModelPermission.Detail",
	PrimaryKey: "",
	PrimaryKeyType: "",
	FieldList: &dbproxy.ObjectFieldList{
		List: []*dbproxy.ObjectField{
			{
				FieldName: "api_list",
				Type:      "string",
				RefType:   "",
				FormName:  "",
				FormType:  "",
				Validate:  "",
				DbDef:     "",
				ScopeCond: "",
				LinkTo:    "",
				Editable:  true,
				IsArray:   true,
			},
		},
	},
}

func init() {
	ObjectTypeList = append(ObjectTypeList, ModelPermissionDetail)
}

var ApiListModelPermissionDetail = &dbproxy.StructField{
	StructFieldName: "ApiList",
	DbFieldName:     "api_list",
}

type ModelPermissionDetailReflect struct {
	ApiList dbproxy.StructFieldWithObj
}

func NewModelPermissionDetailReflect(i interface{}) *ModelPermissionDetailReflect {
	obj := reflect.ValueOf(i)
	if obj.Kind() == reflect.Ptr {
	    obj = obj.Elem()
	}
	r := &ModelPermissionDetailReflect{
		ApiList: dbproxy.StructFieldWithObj{Field: ApiListModelPermissionDetail, Obj: obj},
	}

	return r
}

