// Code generated by rpc_gen. DO NOT EDIT.

package cmltestdb

import (
	"git.pinquest.cn/qlb/brick/dbproxy"
)

var ObjectTypeList []*dbproxy.ModelObjectType
var EnumTypeList []*dbproxy.ModelEnumType

func Register() {
	_ = dbproxy.Register(ObjectTypeList, EnumTypeList)
}
