// Code generated by rpc_gen. DO NOT EDIT.

package cmltestdb

import (
	"git.pinquest.cn/qlb/brick/dbproxy"
)

var ResourceType = &dbproxy.ModelEnumType{
	Name: "cmltest.ResourceType",
	FieldList: &dbproxy.EnumFieldList{
		List: []*dbproxy.EnumField{
			{
				FieldName: "ResourceTypeQrobot",
				IntValue:  1,
				FormName:  "",
			},
			{
				FieldName: "ResourceTypeHostAccount",
				IntValue:  2,
				FormName:  "",
			},
		},
	},
}

func init() {
	EnumTypeList = append(EnumTypeList, ResourceType)
}

